broker_url: "localhost:9092"
security_protocol: "PLAINTEXT"

target_topic: "demo-topic"
group_id: "consumer-kafka-go-local"

schema_registry_url: "http://localhost:8081"
schema_subject: "demo-topic-value"
